sudo: required
language: go
go:
  - "1.11"
go_import_path: github.com/2dust/AndroidLibV2rayLite
git:
  depth: 5
addons:
  apt:
    update: true
before_script:
- sudo ntpdate -u time.google.com
- date
- make all
- make downloadGoMobile
script:
- go test -p 1 -tags json -v github.com/2dust/AndroidLibV2rayLite/...
- make BuildMobile
after_success:
deploy:
  provider: releases
  api_key:
    secure: "WVizcimB4GIOsOrDXhbqdwy96UW3FHmDSAxDi+UE4sXafwLRdoF1b6rNAhGSBjYHSdn4DKbpTEwaImjYwj5Yw6cQlBU29j4KPCPMpEMyrz3vIXF9pM4v6AFW3sieyQWksNLCPPZpM9W57NVW+ta7kwPG3btp1ImxTYLW1DOGkJE7d4a7u+Z7XyJynVf3pRaDnY6SpXRt0o141v3eK/6GEX8W8hOpINaQTfGJLOtVPuQrNw79Rzo1k8OTt2k1a0fUDO3cZPlcBtbfBqX7dqZOANmii8w2YSuLYhzkXHDKiHVjBgPCQ3P9ke0Jmoazasa0+piAQWTDzaNhP92tM1+kPEuhq8c4/F94retOkHCWaif3hG/WQFc0cgQsuV0VOLrAAbcwDwzhUO2HXecwDW5m6sGmvejXG+WNSf6kjr4ifHkE6rqBk+xYOTsiJ8GnNL2w+2ESGgH685gK1T+bwJp2psA9/i08TI9YkIyD18S5rinhITLJD+FtQagwjJTTpinIJp6wasSuWpVHZQVQVnronVsOySRKYVnOxfUm9C47Kk0vGUfhbWNKO/NQY2MAohKIyVSxAq/iOb9up0i4fpRDGheZRyrYuytb3pWgQJ2fmBqM2iy+GGKUQ10+vp4cjXJTkrXzqpqOHgpcS8kQRyGB8prv8w+UvsACxE8PgQmr0MY="
  file:
    - libv2ray.aar
  skip_cleanup: true
  on:
    tags: true
